server:
  port: 7001

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

security:
  oauth2:
    jwt:
      enable: false
      signingKey: 123456
    authServer:
      supportRefreshToken: true
      accessTokenValiditySeconds: 7200
      refreshTokenValiditySeconds: 259200